<?php
/**
 * ListCarrierProducts200ResponseInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zippendo\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zippendo Public API
 *
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).  **Brands (sub-accounts).** An organization can be split into brands, each keeping its own orders, shipments and configuration separate. There are two ways to scope requests to one brand, and NEITHER changes any request body:  1. **Bind the token.** Create an API token with a `brandId` and every request it makes is confined    to that brand — reads filtered, writes stamped. This is the recommended way to give a single    brand's team its own credential. 2. **Send the `X-Zippendo-Brand` header.** An organization-wide token can scope an individual    request by sending the brand's id or slug in this header. Most SDKs let you set it once on the    client so every call inherits it.  A brand-bound token that receives an `X-Zippendo-Brand` header naming a different brand is rejected with `403 BRAND_ACCESS_DENIED` — the binding is never widened. Omit both and requests cover the whole organization, which is the behaviour of every existing token.  Records that belong to no brand carry `brandId: null`. Configuration (carriers, shipping rules, addresses) with a null brand is organization-wide and remains visible inside every brand; orders and shipments with a null brand are only visible organization-wide.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Zippendo\Sdk\Model;

use \ArrayAccess;
use \Zippendo\Sdk\ObjectSerializer;

/**
 * ListCarrierProducts200ResponseInner Class Doc Comment
 *
 * @category Class
 * @package  Zippendo\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ListCarrierProducts200ResponseInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'listCarrierProducts_200_response_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'name' => 'string',
        'product_id' => 'string',
        'type' => 'string',
        'description' => 'string',
        'available_countries' => 'string[]',
        'available_sender_countries' => 'string[]',
        'is_service_point' => 'bool',
        'is_pickup_available' => 'bool',
        'services' => '\Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerServicesInner[]',
        'additional_parameters' => '\Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerAdditionalParametersInner[]',
        'weight_limits' => '\Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerWeightLimits'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'name' => null,
        'product_id' => null,
        'type' => null,
        'description' => null,
        'available_countries' => null,
        'available_sender_countries' => null,
        'is_service_point' => null,
        'is_pickup_available' => null,
        'services' => null,
        'additional_parameters' => null,
        'weight_limits' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'name' => false,
        'product_id' => false,
        'type' => false,
        'description' => false,
        'available_countries' => false,
        'available_sender_countries' => false,
        'is_service_point' => false,
        'is_pickup_available' => false,
        'services' => false,
        'additional_parameters' => false,
        'weight_limits' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'product_id' => 'productId',
        'type' => 'type',
        'description' => 'description',
        'available_countries' => 'availableCountries',
        'available_sender_countries' => 'availableSenderCountries',
        'is_service_point' => 'isServicePoint',
        'is_pickup_available' => 'isPickupAvailable',
        'services' => 'services',
        'additional_parameters' => 'additionalParameters',
        'weight_limits' => 'weightLimits'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'product_id' => 'setProductId',
        'type' => 'setType',
        'description' => 'setDescription',
        'available_countries' => 'setAvailableCountries',
        'available_sender_countries' => 'setAvailableSenderCountries',
        'is_service_point' => 'setIsServicePoint',
        'is_pickup_available' => 'setIsPickupAvailable',
        'services' => 'setServices',
        'additional_parameters' => 'setAdditionalParameters',
        'weight_limits' => 'setWeightLimits'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'product_id' => 'getProductId',
        'type' => 'getType',
        'description' => 'getDescription',
        'available_countries' => 'getAvailableCountries',
        'available_sender_countries' => 'getAvailableSenderCountries',
        'is_service_point' => 'getIsServicePoint',
        'is_pickup_available' => 'getIsPickupAvailable',
        'services' => 'getServices',
        'additional_parameters' => 'getAdditionalParameters',
        'weight_limits' => 'getWeightLimits'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const TYPE_OUTBOUND = 'outbound';
    public const TYPE_INBOUND = 'inbound';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_OUTBOUND,
            self::TYPE_INBOUND,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('product_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('available_countries', $data ?? [], null);
        $this->setIfExists('available_sender_countries', $data ?? [], null);
        $this->setIfExists('is_service_point', $data ?? [], false);
        $this->setIfExists('is_pickup_available', $data ?? [], false);
        $this->setIfExists('services', $data ?? [], null);
        $this->setIfExists('additional_parameters', $data ?? [], null);
        $this->setIfExists('weight_limits', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['product_id'] === null) {
            $invalidProperties[] = "'product_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['available_countries'] === null) {
            $invalidProperties[] = "'available_countries' can't be null";
        }
        if ($this->container['available_sender_countries'] === null) {
            $invalidProperties[] = "'available_sender_countries' can't be null";
        }
        if ($this->container['is_service_point'] === null) {
            $invalidProperties[] = "'is_service_point' can't be null";
        }
        if ($this->container['is_pickup_available'] === null) {
            $invalidProperties[] = "'is_pickup_available' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Display name of the shipping product
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id Unique carrier product identifier
     *
     * @return self
     */
    public function setProductId($product_id)
    {
        if (is_null($product_id)) {
            throw new \InvalidArgumentException('non-nullable product_id cannot be null');
        }
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Direction of the shipment for this product
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Description of the shipping product
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets available_countries
     *
     * @return string[]
     */
    public function getAvailableCountries()
    {
        return $this->container['available_countries'];
    }

    /**
     * Sets available_countries
     *
     * @param string[] $available_countries Recipient countries supported by this product
     *
     * @return self
     */
    public function setAvailableCountries($available_countries)
    {
        if (is_null($available_countries)) {
            throw new \InvalidArgumentException('non-nullable available_countries cannot be null');
        }
        $this->container['available_countries'] = $available_countries;

        return $this;
    }

    /**
     * Gets available_sender_countries
     *
     * @return string[]
     */
    public function getAvailableSenderCountries()
    {
        return $this->container['available_sender_countries'];
    }

    /**
     * Sets available_sender_countries
     *
     * @param string[] $available_sender_countries Sender countries supported by this product
     *
     * @return self
     */
    public function setAvailableSenderCountries($available_sender_countries)
    {
        if (is_null($available_sender_countries)) {
            throw new \InvalidArgumentException('non-nullable available_sender_countries cannot be null');
        }
        $this->container['available_sender_countries'] = $available_sender_countries;

        return $this;
    }

    /**
     * Gets is_service_point
     *
     * @return bool
     */
    public function getIsServicePoint()
    {
        return $this->container['is_service_point'];
    }

    /**
     * Sets is_service_point
     *
     * @param bool $is_service_point Whether delivery is to a service point/pickup location
     *
     * @return self
     */
    public function setIsServicePoint($is_service_point)
    {
        if (is_null($is_service_point)) {
            throw new \InvalidArgumentException('non-nullable is_service_point cannot be null');
        }
        $this->container['is_service_point'] = $is_service_point;

        return $this;
    }

    /**
     * Gets is_pickup_available
     *
     * @return bool
     */
    public function getIsPickupAvailable()
    {
        return $this->container['is_pickup_available'];
    }

    /**
     * Sets is_pickup_available
     *
     * @param bool $is_pickup_available Whether carrier pickup is available for this product
     *
     * @return self
     */
    public function setIsPickupAvailable($is_pickup_available)
    {
        if (is_null($is_pickup_available)) {
            throw new \InvalidArgumentException('non-nullable is_pickup_available cannot be null');
        }
        $this->container['is_pickup_available'] = $is_pickup_available;

        return $this;
    }

    /**
     * Gets services
     *
     * @return \Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerServicesInner[]|null
     */
    public function getServices()
    {
        return $this->container['services'];
    }

    /**
     * Sets services
     *
     * @param \Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerServicesInner[]|null $services Additional services available for this product
     *
     * @return self
     */
    public function setServices($services)
    {
        if (is_null($services)) {
            throw new \InvalidArgumentException('non-nullable services cannot be null');
        }
        $this->container['services'] = $services;

        return $this;
    }

    /**
     * Gets additional_parameters
     *
     * @return \Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerAdditionalParametersInner[]|null
     */
    public function getAdditionalParameters()
    {
        return $this->container['additional_parameters'];
    }

    /**
     * Sets additional_parameters
     *
     * @param \Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerAdditionalParametersInner[]|null $additional_parameters Extra parameters that can or must be supplied for this product
     *
     * @return self
     */
    public function setAdditionalParameters($additional_parameters)
    {
        if (is_null($additional_parameters)) {
            throw new \InvalidArgumentException('non-nullable additional_parameters cannot be null');
        }
        $this->container['additional_parameters'] = $additional_parameters;

        return $this;
    }

    /**
     * Gets weight_limits
     *
     * @return \Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerWeightLimits|null
     */
    public function getWeightLimits()
    {
        return $this->container['weight_limits'];
    }

    /**
     * Sets weight_limits
     *
     * @param \Zippendo\Sdk\Model\ListCarrierProducts200ResponseInnerWeightLimits|null $weight_limits weight_limits
     *
     * @return self
     */
    public function setWeightLimits($weight_limits)
    {
        if (is_null($weight_limits)) {
            throw new \InvalidArgumentException('non-nullable weight_limits cannot be null');
        }
        $this->container['weight_limits'] = $weight_limits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


