<?php
/**
 * CreateShippingRuleRequestAdditionalParametersTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zippendo\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zippendo Public API
 *
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zippendo\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateShippingRuleRequestAdditionalParametersTest Class Doc Comment
 *
 * @category    Class
 * @description Carrier-specific extra parameters. Accepts EITHER the &#x60;{ key: value }&#x60; object (preferred) OR the legacy &#x60;[{ name, val }]&#x60; array, so you can migrate on your own schedule. Each key / &#x60;name&#x60; is the carrier parameter &#x60;key&#x60; from the product&#39;s &#x60;additionalParameters[].key&#x60; (e.g. &#x60;returnFunctionality&#x60;).
 * @package     Zippendo\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateShippingRuleRequestAdditionalParametersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateShippingRuleRequestAdditionalParameters"
     */
    public function testCreateShippingRuleRequestAdditionalParameters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
