<?php
/**
 * UpdateOrgBrandingRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Zippendo\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zippendo Public API
 *
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Zippendo\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateOrgBrandingRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateOrgBrandingRequest
 * @package     Zippendo\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateOrgBrandingRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateOrgBrandingRequest"
     */
    public function testUpdateOrgBrandingRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "primary_color"
     */
    public function testPropertyPrimaryColor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "secondary_color"
     */
    public function testPropertySecondaryColor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
