<?php
/**
 * CarriersApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Zippendo\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Zippendo Public API
 *
 * Public API documentation for Zippendo. Authenticate using your API token (Bearer token prefixed with zipp_).
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@zippendo.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Zippendo\Sdk\Test\Api;

use \Zippendo\Sdk\Configuration;
use \Zippendo\Sdk\ApiException;
use \Zippendo\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CarriersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Zippendo\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CarriersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for connectCarrier
     *
     * Connect carrier.
     *
     */
    public function testConnectCarrier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for disconnectCarrier
     *
     * Disconnect carrier.
     *
     */
    public function testDisconnectCarrier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCarrier
     *
     * Get carrier.
     *
     */
    public function testGetCarrier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCarrierProductServicePoints
     *
     * List product service points.
     *
     */
    public function testListCarrierProductServicePoints()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCarrierProducts
     *
     * List carrier products.
     *
     */
    public function testListCarrierProducts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCarriers
     *
     * List carriers.
     *
     */
    public function testListCarriers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCarrier
     *
     * Update carrier.
     *
     */
    public function testUpdateCarrier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
